#!/bin/bash

# This script returns the version of ReEnroll script
# Make sure to set the Extension Attribute Data Type to "String".
# https://github.com/AndrewMBarnett/ReEnroll
# by Andrew Barnett (@andrewmbarnett)
# 09.16.2024

# Path to ReEnroll folder
folder_path="/Library/Application Support/ReEnroll"

# ReEnroll property list file
ReEnrollFile="$folder_path/ReEnroll"

if [ -f "${ReEnrollFile}.plist" ]; then
    ReEnrollEnrolledResults=$(defaults read "${ReEnrollFile}" ReEnrollVersion 2> /dev/null)
    [[ -n "${ReEnrollEnrolledResults}" ]] && echo "<result>${ReEnrollEnrolledResults}</result>"
    [[ -z "${ReEnrollEnrolledResults}" ]] && echo "<result>No ReEnroll version number found</result>"
else
    echo "<result>No ReEnroll Property List file</result>"
fi

exit 0