#!/bin/bash

# This script returns the last run time of ReEnroll script
# Make sure to set the Extension Attribute Data Type to "Date".
# https://github.com/AndrewMBarnett/ReEnroll
# by Andrew Barnett (@andrewmbarnett)
# 09.16.2024

# Path to ReEnroll folder
folder_path="/Library/Application Support/ReEnroll"

# ReEnroll property list file
ReEnrollFile="$folder_path/ReEnroll"

if [ -f "${ReEnrollFile}.plist" ]; then
    ReEnrollEnrolledResults=$(defaults read "${ReEnrollFile}" ReEnrollLastRun | sed 's/.\{6\}$//' 2> /dev/null)
    [[ -n "${ReEnrollEnrolledResults}" ]] && echo "<result>${ReEnrollEnrolledResults}</result>"
    [[ -z "${ReEnrollEnrolledResults}" ]] && echo "<result>No ReEnroll last run time</result>"
else
    echo "<result>No ReEnroll Property List file</result>"
fi

exit 0